Different ML Algo using SCIKIT LEARN

Importing dependencies

In [45]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.preprocessing import LabelEncoder

In [46]:
#taking the dataset from iris dataset
df = sns.load_dataset("iris")

In [47]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [48]:
df.shape

(150, 5)

Splitting the data into X and Y (feaures and labels)

In [49]:
df.iloc[:,0:4]

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [50]:
X = df.iloc[:,0:4].values

In [51]:
print(X)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]
 [5.7 2.8 4.5 1.3]
 [6.3 3.3 4.7 1.6]
 [4.9 2.4 3.3 1. ]
 [6.6 2.9 4.6 1.3]
 [5.2 2.7 3.9 1.4]
 [5.  2.  3.5 1. ]
 [5.9 3.  4.2 1.5]
 [6.  2.2 4.  1. ]
 [6.1 2.9 4.7 1.4]
 [5.6 2.9 3.6 1.3]
 [6.7 3.1 4.4 1.4]
 [5.6 3.  4.5 1.5]
 [5.8 2.7 4.1 1. ]
 [6.2 2.2 4.5 1.5]
 [5.6 2.5 3.9 1.1]
 [5.9 3.2 4.8 1.8]
 [6.1 2.8 4.  1.3]
 [6.3 2.5 4.9 1.5]
 [6.1 2.8 4.7 1.2]
 [6.4 2.9 4.3 1.3]
 [6.6 3.  4.4 1.4]
 [6.8 2.8 4.8 1.4]
 [6.7 3.  5.  1.7]
 [6.  2.9 4.5 1.5]
 [5.7 2.6 3.5 1. ]
 [5.5 2.4 3.8 1.1]
 [5.5 2.4 3.7 1. ]
 [5.8 2.7 3.9 1.2]
 [6.  2.7 5.1 1.6]
 [5.4 3.  4.5 1.5]
 [6.  3.4 4.5 1.6]
 [6.7 3.1 4.7 1.5]
 [6.3 2.3 4.4 1.3]
 [5.6 3.  4.1 1.3]
 [5.5 2.5 4.  1.3]
 [5.5 2.6 4.4 1.2]
 [6.1 3.  4.6 1.4]
 [5.8 2.6 4.  1.2]
 [5.  2.3 3.3 1. ]
 [5.6 2.7 4.2 1.3]
 [5.7 3.  4.2 1.2]
 [5.7 2.9 4.2 1.3]
 [6.2 2.9 4.3 1.3]
 [5.1 2.5 3.  1.1]
 [5.7 2.8 4.1 1.3]
 [6.3 3.3 6.  2.5]
 [5.8 2.7 5.1 1.9]
 [7.1 3.  5.9 2.1]
 [6.3 2.9 5.6 1.8]
 [6.5 3.  5.8 2.2]
 [7.6 3.  6.6 2.1]
 [4.9 2.5 4.5 1.7]
 [7.3 2.9 6.3 1.8]
 [6.7 2.5 5.8 1.8]
 [7.2 3.6 6.1 2.5]
 [6.5 3.2 5.1 2. ]
 [6.4 2.7 5.3 1.9]
 [6.8 3.  5.5 2.1]
 [5.7 2.5 5.  2. ]
 [5.8 2.8 5.1 2.4]
 [6.4 3.2 5.3 2.3]
 [6.5 3.  5.5 1.8]
 [7.7 3.8 6.7 2.2]
 [7.7 2.6 6.9 2.3]
 [6.  2.2 5.  1.5]
 [6.9 3.2 5.7 2.3]
 [5.6 2.8 4.9 2. ]
 [7.7 2.8 6.7 2. ]
 [6.3 2.7 4.9 1.8]
 [6.7 3.3 5.7 2.1]
 [7.2 3.2 6.  1.8]
 [6.2 2.8 4.8 1.8]
 [6.1 3.  4.9 1.8]
 [6.4 2.8 5.6 2.1]
 [7.2 3.  5.8 1.6]
 [7.4 2.8 6.1 1.9]
 [7.9 3.8 6.4 2. ]
 [6.4 2.8 5.6 2.2]
 [6.3 2.8 5.1 1.5]
 [6.1 2.6 5.6 1.4]
 [7.7 3.  6.1 2.3]
 [6.3 3.4 5.6 2.4]
 [6.4 3.1 5.5 1.8]
 [6.  3.  4.8 1.8]
 [6.9 3.1 5.4 2.1]
 [6.7 3.1 5.6 2.4]
 [6.9 3.1 5.1 2.3]
 [5.8 2.7 5.1 1.9]
 [6.8 3.2 5.9 2.3]
 [6.7 3.3 5.7 2.5]
 [6.7 3.  5.2 2.3]
 [6.3 2.5 5.  1.9]
 [6.5 3.  5.2 2. ]
 [6.2 3.4 5.4 2.3]
 [5.9 3.  5.1 1.8]]

Encoding Species

In [52]:
raw_y = df['species']

In [53]:
labelencoder = LabelEncoder()
Y = labelencoder.fit_transform(raw_y)

In [54]:
#Encoded Y(species)
print(Y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]

Splitting the data into Train Test data

In [55]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2)

Training the model using various Algorithm.

* Logistic Regression
* KNeighbor Classifier
* Gaussian Naive Bayes
* Support vector classifier
    - kernel : Sigmoid, Linear, rbf, poly
* Decision Treee Classifier
* Random forest Classifier

In [56]:
#Logistic Regression Model
from sklearn.linear_model import LogisticRegression
logmodel = LogisticRegression()
logmodel.fit(X_train, y_train)

LogisticRegression()

In [57]:
#Evaluating the model
y_logpred = logmodel.predict(X_test)
from sklearn.metrics import confusion_matrix
matrix = confusion_matrix(y_test, y_logpred)
print("The Confusion matrix : ")
print(matrix)

The Confusion matrix :
[[ 8  0  0]
 [ 0  7  2]
 [ 0  2 11]]

In [58]:
26/30

0.8666666666666667

In [59]:
#KNeighborClassifier Algorithm

#Training the model
from sklearn.neighbors import KNeighborsClassifier
classifier_knn = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2)
classifier_knn.fit(X_train, y_train)

KNeighborsClassifier()

In [60]:
#Evaluating the model
y_pred = classifier_knn.predict(X_test)
knmatrix = confusion_matrix(y_test, y_pred)
print("The Confusion matrix : ")
print(knmatrix)

The Confusion matrix :
[[ 8  0  0]
 [ 0  8  1]
 [ 0  0 13]]

In [61]:
29/30

0.9666666666666667

In [62]:
#NAive Bayes Algorithm

#Training the model
from sklearn.naive_bayes import GaussianNB
classifier_nb = GaussianNB()
classifier_nb.fit(X_train,y_train)

GaussianNB()

In [63]:
y_pred = classifier_nb.predict(X_test)
confusion_matrix(y_test, y_pred)

array([[ 8,  0,  0],
       [ 0,  8,  1],
       [ 0,  2, 11]])

In [64]:
27/30

0.9

In [65]:
#Support vector Classifier
#Kernel: Sigmoid

#Training the model
from sklearn.svm import SVC
classifier_svm_sigmoid = SVC(kernel='sigmoid')
classifier_svm_sigmoid.fit(X_train,y_train)

SVC(kernel='sigmoid')

In [66]:
#Evaluating
y_pred = classifier_svm_sigmoid.predict(X_test)
confusion_matrix(y_test, y_pred)

array([[ 8,  0,  0],
       [ 9,  0,  0],
       [13,  0,  0]])

In [67]:
8/30

0.26666666666666666

In [68]:
#Support vector Classifier
#Kernel: Linear

#Training the model
from sklearn.svm import SVC
classifier_svm_linear = SVC(kernel='linear')
classifier_svm_linear.fit(X_train,y_train)

SVC(kernel='linear')

In [69]:
#Model Evaluation

y_pred = classifier_svm_linear.predict(X_test)
confusion_matrix(y_test, y_pred)

array([[ 8,  0,  0],
       [ 0,  7,  2],
       [ 0,  1, 12]])

In [70]:
27/30

0.9

In [71]:
#Support vector Classifier
#Kernel: rbf

#Training the model
from sklearn.svm import SVC
classifier_svm_rbf = SVC(kernel='rbf')
classifier_svm_rbf.fit(X_train,y_train)

SVC()

In [72]:
#Model evaluation
y_pred = classifier_svm_rbf.predict(X_test)
matrix1 = confusion_matrix(y_test, y_pred)
print(matrix1)

[[ 8  0  0]
 [ 0  8  1]
 [ 0  2 11]]

In [73]:
27/30

0.9

In [74]:
#Support vector Classifier
#Kernel: Sigmoid

#Training the model
from sklearn.svm import SVC
classifier_svm_poly = SVC(kernel='poly')
classifier_svm_poly.fit(X_train,y_train)

SVC(kernel='poly')

In [75]:
#Model evaluation

y_pred = classifier_svm_poly.predict(X_test)
matrix2 = confusion_matrix(y_test, y_pred)
print(matrix2)

[[ 8  0  0]
 [ 0  7  2]
 [ 0  0 13]]

In [76]:
28/30

0.9333333333333333

In [77]:
#Decision tree classifier algorithm

#Training the dataset
from sklearn.tree import DecisionTreeClassifier
classifier_dt = DecisionTreeClassifier(criterion = 'entropy')
classifier_dt.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy')

In [78]:
y_pred = classifier_svm_poly.predict(X_test)
matrix3 = confusion_matrix(y_test, y_pred)
print(matrix3)

[[ 8  0  0]
 [ 0  7  2]
 [ 0  0 13]]

In [79]:
28/30

0.9333333333333333

In [80]:
#Random Forest Algorithm 

#Training the model
from sklearn.ensemble import RandomForestClassifier
classifier_rf = RandomForestClassifier(n_estimators = 3, criterion ='entropy')
classifier_rf.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=3)

In [81]:
#Model evaluation

y_pred = classifier_rf.predict(X_test)
matrix4 = confusion_matrix(y_test, y_pred)
print(matrix4)

[[ 8  0  0]
 [ 0  7  2]
 [ 0  1 12]]

In [82]:
27/30

0.9